name: Build Custom MaixPy Firmware

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: 1. Pull Code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: 2. Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake wget python3 python3-pip git gcc-9 g++-9
        pip3 install intelhex --break-system-packages || pip3 install intelhex

    - name: 3. Download Toolchain
      run: |
        wget https://github.com/kendryte/kendryte-gnu-toolchain/releases/download/v8.2.0-20190409/kendryte-toolchain-ubuntu-amd64-8.2.0-20190409.tar.xz
        sudo tar -Jxf kendryte-toolchain-ubuntu-amd64-8.2.0-20190409.tar.xz -C /opt
        echo "/opt/kendryte-toolchain/bin" >> $GITHUB_PATH

    - name: 4. Build Firmware
      run: |
        export CC=gcc-9
        export CXX=g++-9
        cd projects/maixpy_k210
        python3 project.py clean
        python3 project.py build

    - name: 5. Upload Bin File
      uses: actions/upload-artifact@v4
      with:
        name: Custom_MaixPy_Firmware
        path: projects/maixpy_k210/build/*.bin
